reason: fix copying of freesurfer

diff --git a/main b/main
--- a/main
+++ b/main
@@ -23,13 +23,13 @@ time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt 
 # generate csv's for each statistic that can be useful in MLC analyses
 time singularity exec -e docker://brainlife/freesurfer-stats:1.2 ./generateCSV.py
 
-if [ -f ./parc-stats/parc-stats/tracts_STDEV.csv ]; then
-	mkdir raw
-	mv rois/ parcellation-surface/ resliced/ *.txt ./tmp/*.txt ./raw/
-	rm -rf tmp output cortexmap
-	echo "complete"
-	exit 0
-else
-	echo "stats computations failed somewhere. please check logs and derivatives"
-	exit 1
-fi
+ if [ -f ./parc-stats/parc-stats/tracts_STDEV.csv ]; then
+ 	mkdir raw
+ 	mv rois/ parcellation-surface/ resliced/ *.txt ./tmp/*.txt ./raw/
+ 	rm -rf tmp output cortexmap
+ 	echo "complete"
+ 	exit 0
+ else
+ 	echo "stats computations failed somewhere. please check logs and derivatives"
+ 	exit 1
+ fi
